# language_texts.py

texts = {
    "English": {
        "title": "🎧 AI Noise Reducer",
        "subheader": "Denoise your recordings with AI!",
        "upload_audio": "Upload Audio",
        "record_audio": "Record Live Audio",
        "choose_model": "Choose model to apply for denoising:",
        "process_status": "🔄 Processing... Please wait while the denoising is happening.",
        "denoising_complete": "✅ Denoising completed using {model}!",
        "feedback_section": "🗣️ Share Your Feedback",
        "rate_quality": "How would you rate the audio quality after denoising?",
        "submit_feedback": "Submit Feedback",
        "thank_you": "✅ Thank you for your feedback!",
        "view_feedback": "📊 View Submitted Feedback (for testing only)",
        "made_with": "Made with ❤️ for sound clarity"
    },
    "Spanish": {
        "title": "🎧 Reductor de Ruido AI",
        "subheader": "¡Reduce el ruido de tus grabaciones con AI!",
        "upload_audio": "Subir Audio",
        "record_audio": "Grabar Audio en Vivo",
        "choose_model": "Elige el modelo para aplicar la reducción de ruido:",
        "process_status": "🔄 Procesando... Por favor espera mientras se realiza la reducción de ruido.",
        "denoising_complete": "✅ ¡Reducción de ruido completada usando {model}!",
        "feedback_section": "🗣️ Comparte tu Opinión",
        "rate_quality": "¿Cómo calificarías la calidad del audio después de la reducción de ruido?",
        "submit_feedback": "Enviar Comentarios",
        "thank_you": "✅ ¡Gracias por tus comentarios!",
        "view_feedback": "📊 Ver los comentarios enviados (solo para pruebas)",
        "made_with": "Hecho con ❤️ para la claridad del sonido"
    },
    "French": {
        "title": "🎧 Réducteur de Bruit AI",
        "subheader": "Réduisez le bruit de vos enregistrements avec l'IA!",
        "upload_audio": "Télécharger Audio",
        "record_audio": "Enregistrer Audio en Direct",
        "choose_model": "Choisissez le modèle à appliquer pour la réduction du bruit:",
        "process_status": "🔄 Traitement en cours... Veuillez patienter pendant que la réduction du bruit est en cours.",
        "denoising_complete": "✅ Réduction du bruit terminée avec {model}!",
        "feedback_section": "🗣️ Partagez votre avis",
        "rate_quality": "Comment évaluez-vous la qualité de l'audio après la réduction du bruit?",
        "submit_feedback": "Soumettre des Commentaires",
        "thank_you": "✅ Merci pour vos commentaires!",
        "view_feedback": "📊 Voir les commentaires soumis (pour tests seulement)",
        "made_with": "Fait avec ❤️ pour la clarté sonore"
    },
    "Marathi": {
        "title": "🎧 एआय आवाज कमी करणारा",
        "subheader": "तुमच्या रेकॉर्डिंगचे एआयने आवाज कमी करा!",
        "upload_audio": "ऑडिओ अपलोड करा",
        "record_audio": "लाइव्ह ऑडिओ रेकॉर्ड करा",
        "choose_model": "आवाज कमी करण्यासाठी मॉडेल निवडा:",
        "process_status": "🔄 प्रोसेसिंग... कृपया थोडा वेळ थांबा.",
        "denoising_complete": "✅ आवाज कमी करणं पूर्ण झालं {model} वापरून!",
        "feedback_section": "🗣️ तुमचं अभिप्राय द्या",
        "rate_quality": "आवाजाची गुणवत्ता कशी आहे?",
        "submit_feedback": "अभिप्राय सबमिट करा",
        "thank_you": "✅ तुमच्या अभिप्रायाबद्दल धन्यवाद!",
        "view_feedback": "📊 सबमिट केलेले अभिप्राय पाहा (फक्त चाचणीसाठी)",
        "made_with": "आवाजाच्या स्पष्टतेसाठी ❤️ ने बनवले आहे"
    },
    "Hindi": {
        "title": "🎧 एआई शोर कम करने वाला",
        "subheader": "अपने रिकॉर्डिंग को एआई से शोर मुक्त करें!",
        "upload_audio": "ऑडियो अपलोड करें",
        "record_audio": "लाइव ऑडियो रिकॉर्ड करें",
        "choose_model": "शोर कम करने के लिए मॉडल चुनें:",
        "process_status": "🔄 प्रोसेसिंग... कृपया प्रतीक्षा करें।",
        "denoising_complete": "✅ शोर कम करना {model} का उपयोग करके पूरा हुआ!",
        "feedback_section": "🗣️ अपना फीडबैक दें",
        "rate_quality": "ऑडियो की गुणवत्ता को आप कैसे रेट करेंगे?",
        "submit_feedback": "फीडबैक सबमिट करें",
        "thank_you": "✅ आपके फीडबैक के लिए धन्यवाद!",
        "view_feedback": "📊 सबमिट किए गए फीडबैक देखें (केवल परीक्षण के लिए)",
        "made_with": "ध्वनि की स्पष्टता के लिए ❤️ से बनाया गया"
    },
}
